In [48]:
#1. Create an array of the integers from 10 to 50

import numpy as np
import pandas as pd

In [2]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
#2. Create a 3x3 matrix with values ranging from 0 to 8
data = np.arange(0,9)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
data.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
#3. Create an array of 20 linearly spaced points between 0 and 1, like the one below:
        #array([0. , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
            #0.26315789, 0.31578947, 0.36842105, 0.42105263,
            #0.47368421, 0.52631579, 0.57894737, 0.63157895, 0.68421053,
            #0.73684211, 0.78947368, 0.84210526, 0.89473684, 0.94736842,
            #1. ])
            
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [10]:
info = np.arange(1,26).reshape(5,5)
info

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
#4. bring out the following from data above
        #array([[12, 13, 14, 15],
            #[17, 18, 19, 20],
            #[22, 23, 24, 25]])

info[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [17]:
#5. produce the output below from the data above
        #array([[ 2],
            #[ 7],
            #[12]])
info[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [18]:
#6. Produce the output below from the data above
        #array([21, 22, 23, 24, 25])
info[4]

array([21, 22, 23, 24, 25])

In [25]:
info[0:,4].reshape(5,1)    #Bonus

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [47]:
#7. Get the sum of all the values in the data across the rows

info.sum(axis=0).reshape(5,1)

array([[55],
       [60],
       [65],
       [70],
       [75]])

In [46]:
#8. Get the sum of all the columns in data down the columns

info.sum(axis=1).reshape(5,1)   #Sum across columns

array([[ 15],
       [ 40],
       [ 65],
       [ 90],
       [115]])

In [49]:
#9. Accept input from the user and generate a multiplication table based on the value entered by the user.
    #Eg. If user entered 2, it should generate
        #2x1 =2
        #2x2-4
        #…
        #Up to 2 x 12 = 24

x = 2        
while x <= 24:  
    print(x)
    x += 2


2
4
6
8
10
12
14
16
18
20
22
24


In [50]:
#10. Create a program that counts the number of vowels in a string

def countvowels(string):
    num_vowels=0
    for char in string:
        if char in "aeiouAEIOU":
           num_vowels = num_vowels+1
    return num_vowels

In [55]:
countvowels("Fuleisamazing")     #verify

6