In [3]:
#Numpy (Numerical Python): Python library used for working with arrays - works best with sample data
import numpy as np

In [4]:
data = [1,2,3,4,5,6]    #1demionsional array
info = [[1,2,3,4,5,6]]  #2dimensional array
info

[[1, 2, 3, 4, 5, 6]]

In [5]:
np.array(info)

array([[1, 2, 3, 4, 5, 6]])

In [6]:
df = [[1,2,3], [4,5,6],[7,8,9]]
df

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
#arange: for generating a range of numbers

np.array(df)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [12]:
#Linspace: generates evenly spaced numbers from the start to the final value
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [15]:
#Random: for generating random number
np.random.randint(10)

3

In [16]:
np.random.randint(1,10,5)

array([6, 6, 7, 7, 2])

In [17]:
#rand: generate random number between zero and 1
np.random.rand(10)

array([0.8272871 , 0.56168992, 0.79452967, 0.33682561, 0.1386047 ,
       0.58898849, 0.77641048, 0.40808248, 0.0279115 , 0.20847525])

In [18]:
np.random.rand(5,5)

array([[0.41030916, 0.81421327, 0.88703686, 0.52065026, 0.13505007],
       [0.7560245 , 0.66543968, 0.81657774, 0.13162336, 0.63253887],
       [0.75040742, 0.35529499, 0.0238814 , 0.88233505, 0.5038522 ],
       [0.08845051, 0.64302115, 0.51594316, 0.31525475, 0.56413562],
       [0.65210516, 0.20607632, 0.40200764, 0.03310879, 0.98711404]])

In [19]:
np.random.rand(3,5)

array([[0.06487058, 0.74912434, 0.53282539, 0.05648039, 0.78795967],
       [0.83993033, 0.06043827, 0.18799822, 0.1261107 , 0.17845994],
       [0.96739044, 0.01081705, 0.98854919, 0.70664405, 0.58754988]])

In [20]:
np.random.rand(5,3)

array([[0.66728376, 0.54766319, 0.99974554],
       [0.64491696, 0.12187085, 0.33990005],
       [0.94589293, 0.64381931, 0.37624209],
       [0.06348381, 0.56011933, 0.23796186],
       [0.16457302, 0.37662803, 0.28943871]])

In [21]:
#Randn: generates a random sample from normal standard distribution - can be negative and greater than 1.
np.random.randn(2)

array([-2.22153196, -0.24659063])

In [22]:
np.random.seed(10)     #seed sets the same random result - so that the random number generated doesn't change
np.random.randn(5,5)

array([[ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385,  0.62133597],
       [-0.72008556,  0.26551159,  0.10854853,  0.00429143, -0.17460021],
       [ 0.43302619,  1.20303737, -0.96506567,  1.02827408,  0.22863013],
       [ 0.44513761, -1.13660221,  0.13513688,  1.484537  , -1.07980489],
       [-1.97772828, -1.7433723 ,  0.26607016,  2.38496733,  1.12369125]])

In [23]:
#Numpy array attributes and method
numbers = np.arange(25)
numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
numbers.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
np.arange(12)
#This can be reshaped into 2x6, 3x4, 4x3, 6x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
#Indexing and Slicing of numpy array
record = np.arange(1,15,2)
record

array([ 1,  3,  5,  7,  9, 11, 13])

In [27]:
record[4]   #indexing

9

In [28]:
record[3:6] #SLicing

array([ 7,  9, 11])

In [29]:
info = np.array(([5,10,5], [20,25,30], [35,40,45]))
info

array([[ 5, 10,  5],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
info[1][2]  #indexing

30

In [31]:
info[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [32]:
info[1:3]   #

array([[20, 25, 30],
       [35, 40, 45]])

In [33]:
info[1:3,1:3]

array([[25, 30],
       [40, 45]])

In [34]:
info[1:,1:]

array([[25, 30],
       [40, 45]])

In [35]:
sample = np.arange(1,11)
sample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
#conditional selection in Numpy
sample > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [37]:
sample[sample > 4]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
(sample > 2) & (sample < 6)

array([False, False,  True,  True,  True, False, False, False, False,
       False])

In [39]:
sample[(sample > 2) & (sample < 6)]

array([3, 4, 5])

In [40]:
#Arithmetic Operation
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
num1 = [1,2,3]
num2 = [4,5,6]
num1 + num2

[1, 2, 3, 4, 5, 6]

In [42]:
b = np.arange(1,4)
b

array([1, 2, 3])

In [43]:
c = np.arange(4,7)
c

array([4, 5, 6])

In [44]:
b + c

array([5, 7, 9])

In [45]:
#Universal functions
np.sqrt(9)

3.0

In [46]:
np.square(4)

16

In [47]:
b.sum()

6

In [48]:
b.mean()

2.0

In [49]:
b.max()

3

In [50]:
#Axis logic
arr_2d = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
arr_2d.sum()       #sums all

78

In [52]:
arr_2d.sum(axis=0) #sums column-wise (from top to bottom)

array([15, 18, 21, 24])

In [53]:
arr_2d.sum(axis=1) #sums row-wise (from left to right)

array([10, 26, 42])